apiVersion: v1
kind: Service
metadata:
  name: clusterip-webservice
  labels:
    tier: backend
    service: api
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    tier: backend
    service: api
