apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-webservice
  labels:
    tier: backend
    service: api
spec:
  type: LoadBalancer # only works on supported cloud platforms: AWS, GCP, Azure, etc.
  ports:
    - targetPort: 80
      port: 80
  selector:
    service: api
    tier: backend
